export const languages = [
  { name: "Unknown", value: "Unknown" },
  { name: "C", value: "c" },
  { name: "C++", value: "cpp" },
  { name: "Python", value: "python" },
  { name: "JavaScript", value: "javascript" },
  { name: "Java", value: "java" },
  { name: "C#", value: "csharp" },
  { name: "Ruby", value: "ruby" },
  { name: "Go", value: "go" },
  { name: "PHP", value: "php" },
  { name: "Swift", value: "swift" },
  { name: "Kotlin", value: "kotlin" },
  { name: "TypeScript", value: "typescript" },
  { name: "Rust", value: "rust" },
  { name: "HTML", value: "html" },
  { name: "CSS", value: "css" },
  { name: "SQL", value: "sql" },
  { name: "R", value: "r" },
  { name: "Dart", value: "dart" },
  { name: "Scala", value: "scala" },
  { name: "Perl", value: "perl" },
];